import { IProductsEntity } from "oneentry/dist/products/productsInterfaces";
import { IPagesEntity } from "oneentry/dist/pages/pagesInterfaces";

// Minimal, realistic fixtures that satisfy the oneentry interfaces used across the app.
export const dummyProducts: IProductsEntity[] = [
  {
    id: 1,
    localizeInfos: {
      title: "Margherita Pizza",
      menuTitle: "Margherita",
      htmlContent: "",
      plainContent: "",
    },
    statusIdentifier: "in_stock",
    statusLocalizeInfos: { en_US: { title: "In stock" } },
    attributeSetIdentifier: "default",
    moduleFormConfigs: [],
    position: 1,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 12.99,
    additional: { prices: { min: 12.99, max: 12.99 } },
    sku: "MARG-001",
    isSync: true,
    attributeValues: {
      p_title: {
        type: "string",
        value: "Classic Margherita",
        position: 0,
        additionalFields: [],
      },
      p_description: {
        type: "html",
        value: [
          { htmlValue: "Fresh tomatoes, mozzarella, basil, and olive oil" },
        ],
        position: 1,
        additionalFields: [],
      },
      p_price: {
        type: "number",
        value: 12.99,
        position: 2,
        additionalFields: [],
      },
      p_image: {
        type: "file",
        value: {
          downloadLink:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR0Lj3_8eh0xYQLDhyh1pYwOF6l00mL7hIfww&s",
        },
        position: 3,
        additionalFields: [],
      },
      p_available: {
        type: "list",
        value: [{ title: "Available" }],
        position: 4,
        additionalFields: [],
      },
      // Stock/quantity for this product (used by cart / availability logic)
      p_stock: {
        type: "number",
        value: 12,
        position: 5,
        additionalFields: [],
      },
      // Ingredients and calorie info for display
      p_ingredients: {
        type: "string",
        value: "Tomato, Mozzarella, Basil, Olive Oil",
        position: 6,
        additionalFields: [],
      },
      p_calories: {
        type: "number",
        value: 780,
        position: 7,
        additionalFields: [],
      },
    },
    categories: ["classic-pizzas"],
    isVisible: true,
    productPages: [],
    blocks: [],
    isPositionLocked: false,
    relatedIds: [],
  },
  {
    id: 2,
    localizeInfos: {
      title: "Pepperoni Pizza",
      menuTitle: "Pepperoni",
      htmlContent: "",
      plainContent: "",
    },
    statusIdentifier: "in_stock",
    statusLocalizeInfos: { en_US: { title: "In stock" } },
    attributeSetIdentifier: "default",
    moduleFormConfigs: [],
    position: 2,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 14.99,
    additional: { prices: { min: 14.99, max: 14.99 } },
    sku: "PEP-001",
    isSync: true,
    attributeValues: {
      p_title: {
        type: "string",
        value: "Spicy Pepperoni",
        position: 0,
        additionalFields: [],
      },
      p_description: {
        type: "html",
        value: [{ htmlValue: "Tomato sauce, mozzarella, spicy pepperoni." }],
        position: 1,
        additionalFields: [],
      },
      p_price: {
        type: "number",
        value: 14.99,
        position: 2,
        additionalFields: [],
      },
      p_image: {
        type: "file",
        value: {
          downloadLink:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWR_IcdzoJBxh2nV-UKzdfxEv8zqkDb6qbfQ&s",
        },
        position: 3,
        additionalFields: [],
      },
      p_available: {
        type: "list",
        value: [{ title: "Available" }],
        position: 4,
        additionalFields: [],
      },
      p_stock: {
        type: "number",
        value: 5,
        position: 5,
        additionalFields: [],
      },
      p_ingredients: {
        type: "string",
        value: "Tomato, Mozzarella, Pepperoni, Oregano",
        position: 6,
        additionalFields: [],
      },
      p_calories: {
        type: "number",
        value: 920,
        position: 7,
        additionalFields: [],
      },
    },
    categories: ["classic-pizzas"],
    isVisible: true,
  },
  // Additional sample pizzas
  {
    id: 3,
    localizeInfos: {
      title: "Four Cheese Pizza",
      menuTitle: "Four Cheese",
      htmlContent: "",
      plainContent: "",
    },
    statusIdentifier: "in_stock",
    statusLocalizeInfos: { en_US: { title: "In stock" } },
    attributeSetIdentifier: "default",
    moduleFormConfigs: [],
    position: 3,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 15.5,
    additional: { prices: { min: 15.5, max: 15.5 } },
    sku: "4CH-001",
    isSync: true,
    attributeValues: {
      p_title: {
        type: "string",
        value: "Four Cheese Pizza",
        position: 0,
        additionalFields: [],
      },
      p_description: {
        type: "html",
        value: [{ htmlValue: "Mozzarella, Parmesan, Gorgonzola, Ricotta" }],
        position: 1,
        additionalFields: [],
      },
      p_price: {
        type: "number",
        value: 15.5,
        position: 2,
        additionalFields: [],
      },
      p_image: {
        type: "file",
        value: {
          downloadLink:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgjyPZdku4nqdXZylja8lKOyzNuCCc8btBsw&s",
        },
        position: 3,
        additionalFields: [],
      },
      p_available: {
        type: "list",
        value: [{ title: "Available" }],
        position: 4,
        additionalFields: [],
      },
      p_stock: { type: "number", value: 8, position: 5, additionalFields: [] },
      p_ingredients: {
        type: "string",
        value: "Mozzarella, Parmesan, Gorgonzola, Ricotta",
        position: 6,
        additionalFields: [],
      },
      p_calories: {
        type: "number",
        value: 850,
        position: 7,
        additionalFields: [],
      },
    },
    categories: ["classic-pizzas"],
    isVisible: true,
  },
  {
    id: 4,
    localizeInfos: {
      title: "Hawaiian Pizza",
      menuTitle: "Hawaiian",
      htmlContent: "",
      plainContent: "",
    },
    statusIdentifier: "out_of_stock",
    statusLocalizeInfos: { en_US: { title: "Out of stock" } },
    attributeSetIdentifier: "default",
    moduleFormConfigs: [],
    position: 4,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 14.0,
    additional: { prices: { min: 14.0, max: 14.0 } },
    sku: "HAW-001",
    isSync: true,
    attributeValues: {
      p_title: {
        type: "string",
        value: "Hawaiian Pizza",
        position: 0,
        additionalFields: [],
      },
      p_description: {
        type: "html",
        value: [{ htmlValue: "Tomato, Mozzarella, Ham, Pineapple" }],
        position: 1,
        additionalFields: [],
      },
      p_price: {
        type: "number",
        value: 14.0,
        position: 2,
        additionalFields: [],
      },
      p_image: {
        type: "file",
        value: {
          downloadLink:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgjyPZdku4nqdXZylja8lKOyzNuCCc8btBsw&s",
        },
        position: 3,
        additionalFields: [],
      },
      p_available: {
        type: "list",
        value: [{ title: "Out of Stock" }],
        position: 4,
        additionalFields: [],
      },
      p_stock: { type: "number", value: 0, position: 5, additionalFields: [] },
      p_ingredients: {
        type: "string",
        value: "Tomato, Mozzarella, Ham, Pineapple",
        position: 6,
        additionalFields: [],
      },
      p_calories: {
        type: "number",
        value: 800,
        position: 7,
        additionalFields: [],
      },
    },
    categories: ["specialty-pizzas"],
    isVisible: true,
  },
  {
    id: 5,
    localizeInfos: {
      title: "BBQ Chicken Pizza",
      menuTitle: "BBQ Chicken",
      htmlContent: "",
      plainContent: "",
    },
    statusIdentifier: "in_stock",
    statusLocalizeInfos: { en_US: { title: "In stock" } },
    attributeSetIdentifier: "default",
    moduleFormConfigs: [],
    position: 5,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 16.25,
    additional: { prices: { min: 16.25, max: 16.25 } },
    sku: "BBQ-001",
    isSync: true,
    attributeValues: {
      p_title: {
        type: "string",
        value: "BBQ Chicken Pizza",
        position: 0,
        additionalFields: [],
      },
      p_description: {
        type: "html",
        value: [{ htmlValue: "BBQ sauce, Chicken, Red Onion, Cilantro" }],
        position: 1,
        additionalFields: [],
      },
      p_price: {
        type: "number",
        value: 16.25,
        position: 2,
        additionalFields: [],
      },
      p_image: {
        type: "file",
        value: { downloadLink: "https://example.com/images/bbqchicken.jpg" },
        position: 3,
        additionalFields: [],
      },
      p_available: {
        type: "list",
        value: [{ title: "Available" }],
        position: 4,
        additionalFields: [],
      },
      p_stock: { type: "number", value: 3, position: 5, additionalFields: [] },
      p_ingredients: {
        type: "string",
        value: "BBQ sauce, Chicken, Red Onion, Cilantro",
        position: 6,
        additionalFields: [],
      },
      p_calories: {
        type: "number",
        value: 940,
        position: 7,
        additionalFields: [],
      },
    },
    categories: ["specialty-pizzas"],
    isVisible: true,
  },
  {
    id: 6,
    localizeInfos: {
      title: "Vegan Delight",
      menuTitle: "Vegan",
      htmlContent: "",
      plainContent: "",
    },
    statusIdentifier: "in_stock",
    statusLocalizeInfos: { en_US: { title: "In stock" } },
    attributeSetIdentifier: "default",
    moduleFormConfigs: [],
    position: 6,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 13.5,
    additional: { prices: { min: 13.5, max: 13.5 } },
    sku: "VEG-001",
    isSync: true,
    attributeValues: {
      p_title: {
        type: "string",
        value: "Vegan Delight",
        position: 0,
        additionalFields: [],
      },
      p_description: {
        type: "html",
        value: [{ htmlValue: "Tomato, Vegan Cheese, Bell Peppers, Olives" }],
        position: 1,
        additionalFields: [],
      },
      p_price: {
        type: "number",
        value: 13.5,
        position: 2,
        additionalFields: [],
      },
      p_image: {
        type: "file",
        value: {
          downloadLink:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgjyPZdku4nqdXZylja8lKOyzNuCCc8btBsw&s",
        },
        position: 3,
        additionalFields: [],
      },
      p_available: {
        type: "list",
        value: [{ title: "Available" }],
        position: 4,
        additionalFields: [],
      },
      p_stock: { type: "number", value: 20, position: 5, additionalFields: [] },
      p_ingredients: {
        type: "string",
        value: "Tomato, Vegan Cheese, Bell Peppers, Olives",
        position: 6,
        additionalFields: [],
      },
      p_calories: {
        type: "number",
        value: 650,
        position: 7,
        additionalFields: [],
      },
    },
    categories: ["specialty-pizzas"],
    isVisible: true,
  },
  {
    id: 7,
    localizeInfos: {
      title: "Beef Cheese Pizza",
      menuTitle: "Beef Cheese",
      htmlContent: "",
      plainContent: "",
    },
    statusIdentifier: "in_stock",
    statusLocalizeInfos: { en_US: { title: "In stock" } },
    attributeSetIdentifier: "default",
    moduleFormConfigs: [],
    position: 3,
    templateIdentifier: null,
    shortDescTemplateIdentifier: null,
    price: 15.5,
    additional: { prices: { min: 15.5, max: 15.5 } },
    sku: "4CH-001",
    isSync: true,
    attributeValues: {
      p_title: {
        type: "string",
        value: "Four Cheese Pizza",
        position: 0,
        additionalFields: [],
      },
      p_description: {
        type: "html",
        value: [
          { htmlValue: "Mozzarella, Parmesan, Gorgonzola, Ricotta,Beef" },
        ],
        position: 1,
        additionalFields: [],
      },
      p_price: {
        type: "number",
        value: 18.5,
        position: 2,
        additionalFields: [],
      },
      p_image: {
        type: "file",
        value: {
          downloadLink:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgjyPZdku4nqdXZylja8lKOyzNuCCc8btBsw&s",
        },
        position: 3,
        additionalFields: [],
      },
      p_available: {
        type: "list",
        value: [{ title: "Available" }],
        position: 4,
        additionalFields: [],
      },
      p_stock: { type: "number", value: 8, position: 5, additionalFields: [] },
      p_ingredients: {
        type: "string",
        value: "Mozzarella, Parmesan, Gorgonzola, Ricotta",
        position: 6,
        additionalFields: [],
      },
      p_calories: {
        type: "number",
        value: 850,
        position: 7,
        additionalFields: [],
      },
    },
    categories: ["classic-pizzas"],
    isVisible: true,
  },
];

export const dummyCatalogs: IPagesEntity[] = [
  {
    id: 100,
    parentId: null,
    pageUrl: "classic-pizzas",
    depth: 0,
    localizeInfos: {
      title: "Classic Pizzas",
      menuTitle: "Classic",
      htmlContent: "",
      plainContent: "",
    },
    isVisible: true,
    blocks: [],
    forms: [],
    type: "catalog_page",
    templateIdentifier: null,
    attributeSetIdentifier: "page",
    attributeValues: {},
    moduleFormConfigs: [],
    isSync: true,
    position: 1,
    config: { rowsPerPage: 3, productsPerRow: 4 },
    products: 2,
    childrenCount: 0,
    total: 2,
    categoryPath: "Classic Pizzas",
  },
  {
    id: 101,
    parentId: null,
    pageUrl: "specialty-pizzas",
    depth: 0,
    localizeInfos: {
      title: "Specialty Pizzas",
      menuTitle: "Specialty",
      htmlContent: "",
      plainContent: "",
    },
    isVisible: true,
    blocks: [],
    forms: [],
    type: "catalog_page",
    templateIdentifier: null,
    attributeSetIdentifier: "page",
    attributeValues: {},
    moduleFormConfigs: [],
    isSync: true,
    position: 2,
    config: { rowsPerPage: 3, productsPerRow: 4 },
    products: 0,
    childrenCount: 0,
    total: 0,
    categoryPath: "Specialty Pizzas",
  },
];
